[project]
name = "doccrawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logfire>=1.3.0",
    "pandas>=2.2.3",
    "playwright>=1.48.0",
    "psycopg2-binary>=2.9.10",
    "scrapegraphai>=1.27.0",
]
