# config/crawler_config.yaml
# Document Crawler Configuration Guide
#
# This configuration file defines the crawling strategy for different types of document sources.
# Each URL is classified into one of five types (0-4), each with specific behaviors:
#
# Type 0 - Direct Target URLs:
#   - Direct links to target documents (e.g., direct PDF links)
#   - No crawling depth (max_depth must be 0)
#   - No seed_pattern needed
#   - Example use: Known document URLs that don't require crawling
#
# Type 1 - Single Page with Targets:
#   - Pages containing target document links
#   - No crawling depth (max_depth must be 0)
#   - No seed_pattern needed
#   - Uses target_patterns to identify document links
#   - Example use: Archive pages with document listings
#
# Type 2 - Seed and Target Pages:
#   - Pages containing both seed URLs and target documents
#   - Crawls one level deep (max_depth must be 1)
#   - Requires seed_pattern to identify next-level pages
#   - Uses target_patterns to identify documents
#   - Example use: Index pages with links to archive sections
#   - Skip seeds already present in frontier table
#
# Type 3 - Complex AI-Assisted:
#   - Three-level crawling strategy:
#     * Depth 0: Uses seed_pattern and target_patterns
#     * Depth 1: Uses ScrapegraphAI to identify both seeds and targets
#     * Depth 2: Only collects targets matching target_patterns
#   - Requires max_depth = 2
#   - Requires seed_pattern for initial crawling
#   - Skip seeds already present in frontier table
#
# Type 4 - Full AI-Assisted:
#   - Multi-level crawling with AI assistance:
#     * Depth 0-1: Uses ScrapegraphAI to identify both seeds and targets
#     * Final depth: Only collects targets matching target_patterns
#   - Configurable max_depth (must be ≥ 2)
#   - No initial seed_pattern required (fully AI-driven)
#   - Skip seeds already present in frontier table
#
# Common Configuration Elements:
# - target_patterns: List of regex patterns identifying target documents
#   Examples:
#   - ".*\.pdf$" : Matches URLs ending in .pdf
#   - ".*/doc/\d+$" : Matches URLs like "/doc/123"
#   - ".*/document/[a-zA-Z0-9-]+$" : Matches document URLs with alphanumeric IDs
#
# - seed_pattern: Regex pattern identifying URLs to crawl next
#   Examples:
#   - "/archive/\d{4}/$" : Matches year-based archive sections
#   - "/section/[a-zA-Z0-9-]+/$" : Matches section URLs
# Config for Document Crawler
crawler:
  default_settings:
    request_delay: 1.0 # seconds
    timeout: 30 # seconds
    max_concurrent_pages: 5
    batch_size: 10

  categories:
    - name: "Roma La Sapienza"
      description: "Borse di studio e premi di laurea Sapienza"
      urls:
        - url: "https://www.uniroma1.it/it/pagina/premi-tesi-borse-di-studio-e-altre-opportunita?page=1"
          type: 3
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: "https://www.uniroma1.it/it/borsa-di-studio"
          max_depth: 2

        - url: "https://www.uniroma1.it/it/pagina/premi-tesi-borse-di-studio-e-altre-opportunita?page=2"
          type: 3
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: "https://www.uniroma1.it/it/borsa-di-studio"
          max_depth: 2

        - url: "https://www.uniroma1.it/it/pagina/premi-tesi-borse-di-studio-e-altre-opportunita?page=3"
          type: 3
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: "https://www.uniroma1.it/it/borsa-di-studio"
          max_depth: 2

    - name: "Bologna"
      description: "Borse di studio e premi di laurea UniBo"
      urls:
        - url: "https://bandi.unibo.it/agevolazioni/premi-laurea"
          type: 2
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: ".*/agevolazioni/premi-laurea/.*" # Aggiunto un pattern esempio per Type 2
          max_depth: 1

        - url: "https://bandi.unibo.it/agevolazioni/borse?b_start:int=20"
          type: 2
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: ".*/agevolazioni/borse/.*" # Aggiunto un pattern esempio per Type 2
          max_depth: 1

        - url: "https://bandi.unibo.it/agevolazioni/borse"
          type: 2
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: ".*/agevolazioni/borse/.*" # Aggiunto un pattern esempio per Type 2
          max_depth: 1

    - name: "Torino"
      description: "Borse di studio e premi di laurea UniTo"
      urls:
        - url: "https://webapps.unito.it/concorsiweb/visualizzaperweb.php?tipo=25&p=y&C7=all&criterio35=A&criterio46=No"
          type: 1
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: null # Type 1 non richiede seed_pattern
          max_depth: 0

        - url: "https://webapps.unito.it/concorsiweb/visualizzaperweb.php?tipo=24&p=y&C7=all&criterio35=A&criterio46=No"
          type: 1
          target_patterns:
            - ".*\\.pdf$"
          seed_pattern: null # Type 1 non richiede seed_pattern
          max_depth: 0

database:
  frontier_table: "url_frontier"
