# config/crawler_config.yaml
# Document Crawler Configuration Guide
# 
# This configuration file defines the crawling strategy for different types of document sources.
# Each URL is classified into one of five types (0-4), each with specific behaviors:
#
# Type 0 - Direct Target URLs:
#   - Direct links to target documents (e.g., direct PDF links)
#   - No crawling depth (max_depth must be 0)
#   - No seed_pattern needed
#   - Example use: Known document URLs that don't require crawling
#
# Type 1 - Single Page with Targets:
#   - Pages containing target document links
#   - No crawling depth (max_depth must be 0)
#   - No seed_pattern needed
#   - Uses target_patterns to identify document links
#   - Example use: Archive pages with document listings
#
# Type 2 - Seed and Target Pages:
#   - Pages containing both seed URLs and target documents
#   - Crawls one level deep (max_depth must be 1)
#   - Requires seed_pattern to identify next-level pages
#   - Uses target_patterns to identify documents
#   - Example use: Index pages with links to archive sections
#   - Skip seeds already present in frontier table
#
# Type 3 - Complex AI-Assisted:
#   - Three-level crawling strategy:
#     * Depth 0: Uses seed_pattern and target_patterns
#     * Depth 1: Uses ScrapegraphAI to identify both seeds and targets
#     * Depth 2: Only collects targets matching target_patterns
#   - Requires max_depth = 2
#   - Requires seed_pattern for initial crawling
#   - Skip seeds already present in frontier table
#
# Type 4 - Full AI-Assisted:
#   - Multi-level crawling with AI assistance:
#     * Depth 0-1: Uses ScrapegraphAI to identify both seeds and targets
#     * Final depth: Only collects targets matching target_patterns
#   - Configurable max_depth (must be ≥ 2)
#   - No initial seed_pattern required (fully AI-driven)
#   - Skip seeds already present in frontier table
#
# Common Configuration Elements:
# - target_patterns: List of regex patterns identifying target documents
#   Examples:
#   - ".*\.pdf$" : Matches URLs ending in .pdf
#   - ".*/doc/\d+$" : Matches URLs like "/doc/123"
#   - ".*/document/[a-zA-Z0-9-]+$" : Matches document URLs with alphanumeric IDs
#
# - seed_pattern: Regex pattern identifying URLs to crawl next
#   Examples:
#   - "/archive/\d{4}/$" : Matches year-based archive sections
#   - "/section/[a-zA-Z0-9-]+/$" : Matches section URLs

crawler:
  default_settings:
    request_delay: 1.0  # Delay between requests in seconds
    timeout: 30  # Request timeout in seconds

  categories:
    - name: "documenti_ministeriali"
      description: "Documenti e circolari ministeriali"
      urls:
        # Type 0: Direct target URL example
        - url: "https://example.com/docs/circolare123.pdf"
          type: 0
          target_patterns:
            - ".*\.pdf$"
          max_depth: 0
          
        # Type 1: Single page with target URLs
        - url: "https://example.com/documenti-2024"
          type: 1
          target_patterns:
            - ".*\.pdf$"
            - ".*/doc/circolare-\d+$"
          max_depth: 0
          
        # Type 2: Page with both target and seed URLs
        - url: "https://example.com/archivio-circolari"
          type: 2
          target_patterns:
            - ".*\.pdf$"
            - ".*/circolari/\d{4}/\d+$"
          seed_pattern: "/archivio-circolari/\d{4}/$"
          max_depth: 1
          
        # Type 3: Complex crawling with AI assistance at depth 1
        - url: "https://example.com/amministrazione"
          type: 3
          target_patterns:
            - ".*\.pdf$"
            - ".*/documento/[a-zA-Z0-9-]+$"
          seed_pattern: "/amministrazione/[a-zA-Z0-9-]+/$"
          max_depth: 2
          
        # Type 4: Full AI-assisted crawling
        - url: "https://example.com/portale"
          type: 4
          target_patterns:
            - ".*\.pdf$"
            - ".*/files/.*documento.*"
          max_depth: 3

    - name: "documenti_tecnici"
      description: "Documentazione tecnica e specifiche"
      urls:
        - url: "https://example.com/specs/technical_doc_v1.pdf"
          type: 0
          target_patterns:
            - ".*\.pdf$"
          max_depth: 0
          
        - url: "https://example.com/technical-library"
          type: 1
          target_patterns:
            - ".*\.pdf$"
            - ".*/technical-specs/.*"
          max_depth: 0
          
        - url: "https://example.com/documentation"
          type: 2
          target_patterns:
            - ".*\.pdf$"
            - ".*/docs/v\d+/.*"
          seed_pattern: "/documentation/section-.*/$"
          max_depth: 1

database:
  frontier_table: "url_frontier"
